name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Set GCC 11 as default
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11

    - name: Install Valgrind
      run: sudo apt-get install -y valgrind
        
    - name: Build
      run: make
      
    - name: Valgrind Check
      run: make valgrind
      
    - name: Clean
      run: make clean
